### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by asinwang** [huggingface/course#683]
![image](https://github.com/huggingface/course/assets/1953797/09e2fb9e-0ebc-4e15-9a84-13bd8fb7a159)
> npm run custom-svelte-client && vite dev

> kit@0.0.1 custom-svelte-client
> node ./svelteKitCustomClient/replace

Forced re-optimization of dependencies

  VITE v4.5.2  ready in 722 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
NotFound [Error]: Not found: /
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40) {
  status: 404
}

warn - The `@variants` directive has been deprecated in Tailwind CSS v3.0.
warn - Use `@layer utilities` or `@layer components` instead.
warn - https://tailwindcss.com/docs/upgrade-guide#replace-variants-with-layer
NotFound [Error]: Not found: /chapter1/3
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
NotFound [Error]: Not found: /chapter1/6
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
NotFound [Error]: Not found: /chapter1/6
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/private/var/folders/00/j3d6n1nx6t9bbxc_8j_9bkl40000gp/T/tmp5d4m20p1/kit/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}

**Comment by ChenNingCong** [comment]
Hi, I also encountered this problem. It turns out that the doc-builder in the pip repo is out-dated.
Please install and build the doc-builder from scratch [doc-builder](https://github.com/huggingface/doc-builder)
```
cd doc-builder
pip install -e .
```
Then run `doc-builder`.

**Comment by bewygs** [comment]
Hi, I encountered the same issue even when installing doc-builder from the source. I used Python 3.8 and Node version 20 as it seems to be the version used in [doc-builder/.github/workflows](https://github.com/huggingface/doc-builder/tree/main/.github/workflows). 

@ChenNingCong which version of python and node did you use ?

**Comment by confiq** [comment]
@bewygs :

```
❯ python3 --version && node --version
Python 3.12.2
v21.7.1
```
