### ISSUE TITLE
Translation to Russian

### ISSUE THREAD

**Issue by pdumin** [huggingface/course#75]
Hi there 👋

Let's translate the course to Russian so that the whole community can benefit from this resource 🌎!

Below are the chapters and files that need translating - let us know here if you'd like to translate any and we'll add your name to the list. Once you're finished, open a pull request and tag this issue by including `#issue-number` in the description, where `issue-number` is the number of this issue.

> 🙋 If you'd like others to help you with the translation, you can also post in our [forums](https://discuss.huggingface.co/c/course/20) or tag [@_lewtun](https://twitter.com/_lewtun) on Twitter to gain some visibility.

## Chapters

**0 - Setup**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter0/1.mdx)

**1 - Transformer models**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/7.mdx)
- [ ] [`8.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/8.mdx)
- [ ] [`9.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/9.mdx)
- [ ] [`10.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter1/10.mdx)

**2 - Using 🤗 Transformers**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/7.mdx)
- [ ] [`8.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter2/8.mdx)

**3 - Fine-tuning a pretrained model**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/3.mdx)
- [ ] [`3_tf.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/3_tf.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/6.mdx)

**4 - Sharing models and tokenizers**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter4/6.mdx)

**5 - The 🤗 Datasets library**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/7.mdx)
- [ ] [`8.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter5/8.mdx)

**6 -  The 🤗 Tokenizers library**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/3.mdx)
- [ ] [`3b.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/3b.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/7.mdx)
- [ ] [`8.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/8.mdx)
- [ ] [`9.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/9.mdx)
- [ ] [`10.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter6/10.mdx)

**7 - Main NLP tasks**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/4.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/7.mdx)
- [ ] [`8.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/8.mdx)
- [ ] [`9.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter7/9.mdx)

**8 - How to ask for help**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/1.mdx)
- [ ] [`2.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/2.mdx)
- [ ] [`3.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/3.mdx)
- [ ] [`4.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/4.mdx)
- [ ] [`4_tf.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/4_tf.mdx)
- [ ] [`5.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/5.mdx)
- [ ] [`6.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/6.mdx)
- [ ] [`7.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/chapter8/7.mdx)

**Events**
- [ ] [`1.mdx`](https://github.com/huggingface/course/blob/main/chapters/en/event/1.mdx)

**Comment by pdumin** [comment]
I will translate chapters 1 and 2.

**Comment by lewtun** [comment]
I've now deployed the Russian version and you can access it here 🥳 : https://huggingface.co/course/ru/chapter1/1

(We plan to add a button to the dropdown so this can be accessed directly from the English version)

**Comment by pdumin** [comment]
It's great! Thank you!

**Comment by svv73** [comment]
I would like to help translating chapter 2. Now translate section 1.

**Comment by pdumin** [comment]
> I would like to help translating chapter 2. Now translate section 1.

The first chapter is already translated: https://github.com/huggingface/course/pull/98

**Comment by pdumin** [comment]
I'll start translating Chapter 3: Fine-tuning a pretrained model soon.

**Comment by alex-badin** [comment]
Hi everyone! wanna join the ru translation. 
@svv73 , I can finish chapter 2, or please advise if you will.

**Comment by ilnarkz** [comment]
I can participate too, I'll take chapter 8.

**Comment by ilnarkz** [comment]
You have an error.
events/1.mdx does not open. You need to change to https://github.com/huggingface/course/blob/main/chapters/en/events/1.mdx

**Comment by blademoon** [comment]
Good afternoon. I translate and prepare subtitles for the video course.

**Comment by pdumin** [comment]
> Good afternoon. I translate and prepare subtitles for the video course.

Hey! If its possible, please translate chapter 8. I will do the rest.

**Comment by blademoon** [comment]
I translate everything sequentially. This is important in order to keep a coherent and unified style. I plan to do subtitles for all the videos in the course.

**Comment by blademoon** [comment]
> Hey! If its possible, please translate chapter 8. I will do the rest.

I translate everything sequentially. This is important in order to keep a coherent and unified style. I plan to do subtitles for all the videos in the course.

**Comment by pdumin** [comment]
> > Hey! If its possible, please translate chapter 8. I will do the rest.
> 
> I translate everything sequentially. This is important in order to keep a coherent and unified style. I plan to do subtitles for all the videos in the course.

Okay, then I will finish translating the course itself and be able to follow a single notation in my texts. 
Thanks!

**Comment by 501Good** [comment]
Hi! I would like to contribute to the translation. Is chapter 7 free to take on?

**Comment by blademoon** [comment]
@pdumin Hi, do you translate the word "batch" as "пакет" or as "батч"?

**Comment by blademoon** [comment]
@501Good Good afternoon. Are you talking about subtitles? I translate subtitles. We agreed that in order to maintain a consistent and unified style, everyone translates one thing at a time.

**Comment by 501Good** [comment]
> @501Good Good afternoon. Are you talking about subtitles? I translate subtitles. We agreed that in order to maintain a consistent and unified style, everyone translates one thing at a time.

Hi @blademoon! I was talking about the chapters.

**Comment by blademoon** [comment]
@501Good ))) Chapters where? The video is also divided into chapters) Look at (this)[https://www.youtube.com/watch?v=00GKzGyWFEs&list=PLo2EIpI_JMQtNtKNFFSMNIZwspj8H7-sQ].

**Comment by 501Good** [comment]
> @501Good ))) Chapters where? The video is also divided into chapters) Look at [this](https://www.youtube.com/watch?v=00GKzGyWFEs&list=PLo2EIpI_JMQtNtKNFFSMNIZwspj8H7-sQ).

The text version of the course: https://github.com/huggingface/course/tree/main/chapters/ru.

**Comment by blademoon** [comment]
> 

You'd better ask @pdumin about this. I translate subtitles for videos.

**Comment by pdumin** [comment]
@blademoon The idea with the correspondence table is great and really userful. 

@501Good I translated most of the text course. Now in the process of translating the sixth chapter.
You can take chapters 7 and 8, the rest is already done.
Also, any help in checking broken links and any typos will be useful to us. Please let me know what you are going to do.

**Comment by 501Good** [comment]
@pdumin I have started with proofreading. I will go through chapters 0-5 then, and after, take chapters 7 and 8 for translation if no one takes them by then. Like this, I will also be more familiar with the language that you used so that my translations can fit better.
I have also noticed that the English text has been updated in some places (e.g. new people in Chapter 1, Lesson 1), so I will add missing parts as well.

**Comment by blademoon** [comment]
@pdumin Need to push through the creation of the folder "course/subtitles/ru" and the subtitle files for chapter 1 of the video course. I did. But I need the folder "../ru/" to add chapter 2. How do I do this?

**Comment by blademoon** [comment]
> @blademoon The idea with the correspondence table is great and really userful.

Can you create a document on Google Disk or are there alternative sites?

**Comment by pdumin** [comment]
> @pdumin Need to push through the creation of the folder "course/subtitles/ru" and the subtitle files for chapter 1 of the video course. I did. But I need the folder "../ru/" to add chapter 2. How do I do this?

You can just make a copy of `en` folder and replace content in corresponding files. It works for text course.

@501Good It will be nice if you create this file and drop a link to it here. Please mention usernames here so we can commit the changes. Also, if you find typos and errors, make commits immediately, in which case we will be able to keep the translation up to date.


Thanks everyone for the help.

**Comment by blademoon** [comment]
> You can just make a copy of en folder and replace content in corresponding files. It works for text course.

@pdumin I create [this](https://github.com/huggingface/course/pull/480). As i undestand this is correct way to create file and folder for russian subtitles. I must delet this and cdo like you say?

**Comment by blademoon** [comment]
> No, I think you did everything right. Anyway, the hugginface members will be able to comment if there are any errors.

OK. But the folder still hasn't appeared... With the first chapter of the video course.

**Comment by pdumin** [comment]
@blademoon This takes some time and verification, usually can take several days.

**Comment by blademoon** [comment]
@pdumin OK. I have finished translating the subtitles for chapter 2 of the video course. I will make the STR files today.
I decided it's probably better to translate "batch" as "батч".

**Comment by blademoon** [comment]
@pdumin @501Good https://github.com/huggingface/course/pull/489

**Comment by 501Good** [comment]
@pdumin Several sections are missing from chapter 2, do you mind if I take over their translation and proofread existing sections in chapter 2?

**Comment by pdumin** [comment]
@501Good These sections were supposed to be translated by other users, but apparently not translated. If you want, you can supplement their results.

I'm sorry, I didn't follow this.

**Comment by blademoon** [comment]
@501Good @pdumin 
Mask Filling | предсказание замаскированного токена - точно речь не про "заполнение маски"?

Model Hub | Model Hub	- хаб моделей

| Padding | padding / выравнивание - здесь речь идёт про дополнение предложений, может лучше переводит как "дополнение/заполнение"?
Токен заполнения, Токен дополнения... Это как Truncate - обрезка/подрезка...

Summarization | автоматическое реферирование - здесь спорный момент! Вообще это "резюмирование текста", то есть составление кракого варианта. Но на практике я чаще встречал перевод образованием неологизма - "суммаризация текста".

Может лучше так? Как считаете?

**Comment by 501Good** [comment]
@blademoon 

- **Mask Filling** | Тоже изначально думал про "заполнение маски", но звучит немного непонятно, если честно, поэтому выбрал описательный оборот. Хотя и английский вариант mask filling тоже кажется не совсем очевидным. Если "заполнение маски" часто применяется в русскоязычной среде, тогда лучше применять его, хотя я встречал и "предсказание замаскированного токена" или "восстановление маскированного токена". Возможно, лучше тогда делать уточнение, типа "заполнение маски (пропуска)" или "заполнение маски-пропуска"?
- **Model Hub** | Это [часть экосистемы Hugging Face](https://huggingface.co/docs/hub/models-the-hub), то есть скорее имя собственное.
- **Padding** | Не будет ли в таком случае "заполнение" вызывать путаницу с "заполнением маски"? Мне кажется, что "выравнивание" больше подходит здесь по смыслу, так как padding используется, чтобы сделать все последовательности в батче одинаковой длины. Тогда padding как существительное будет "токен выравнивания".
- **Summarization** | Согласен, "резюмирование" или "суммаризация" звучат лучше, чем "реферирование". Тут я ориентировался на [русскую страницу Википедии](https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%80%D0%B5%D1%84%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5).

**Comment by pdumin** [comment]
@blademoon 

* **Mask Filling** | Мне хорошим вариантом кажется «восстановление (предсказание) маскированного токена», такой вариант я встречал чаще, но готов к любому из предложенных. 
* **Model Hub** оставил бы Model Hub. В целом, если все же стремиться к русскому, то «репозиторий моделей» Hugging Face. 
* **Padding** | Мне крайне непривычно слышать «выравнивание», «padding» / «пэддинг» есть и в свертках, и там его вроде бы так и называют. Но вновь, если кто-то уверен, что это недопустимо – готов на более приемлемый для вас вариант. 
* **Саммаризация**, кажется, уже плотно вошло в лексикон. И рефрерирование, и резюмирование кажутся мне косноязычными, я бы оставли «саммаризация».

**Comment by blademoon** [comment]
@pdumin @501Good 
- Model Hub | Есть у меня предположение, что здесь просто наши англоязычные коллеги просто написали оба слова с большой буквы. Потому, что особого смысла превращать "хаб моделей" в название (имя собственное) не вижу смысла. Он все равно останется хабом моделей.
- Padding | padding | Вот тут есть проблема, когда это имя атрибута/параметра/опции - то это никак не переведится. А вот в тексте где идёт описание процесса, можно получить "падинг на падинге сидит и падингом погоняет"...
- Summarization | Согласен с вами, давайте просто оставим "суммаризация". 

Вообще, в субтитрах написание некоторых слов с большой буквы у меня порой много вопросов вызывает. Есть подозрение что это особенности процесса транскрибации с помощью нейронной сети. Ведь получить нормальное предложение c пунктуацией (насколько я знаю) можно только с помощью [Whisper](https://github.com/openai/whisper). Но у него есть особенность. Он порою может ошибиться с расстановкой заглавных букв. Таким образом "model hub Hugging Face" может легко стать "Mode Hub Hugging Face". Но логический, в этом нет никакого смысла.

**Comment by blademoon** [comment]
@501Good @pdumin Насчёт Mask Filling тоже, а не являются ли заглавные буквы результатом транскрибации?

**Comment by blademoon** [comment]
@501Good @pdumin Субтитры все буду переделывать. Неверный подход выбрал. Нужно все же оставить разбивку на короткие строки а не предложения целиком, в некоторых местах предложения получаются слишком длинные (занимают пол экрана).

**Comment by blademoon** [comment]
@501Good Good afternoon. Can you post here a direct link to the translation glossary file we agreed on? So that you can find it quickly.

**Comment by 501Good** [comment]
Hi @blademoon! I keep the updated glossary [here](https://github.com/501Good/course/blob/feature/glossary/chapters/ru/glossary/1.mdx).

**Comment by blademoon** [comment]
@pdumin Можешь добавить в список задач и субтитры по частям? Я делаю.

**Comment by blademoon** [comment]
@501Good 

Encoder - кодировщик/[кодер](http://rus-yaz.niv.ru/doc/foreign-words-komlev/fc/slovar-202-1.htm#zag-1060) (Словарь иностранных слов. Комлев Н.Г., 2006)
Decoder - декодировщик/[декодер](http://rus-yaz.niv.ru/doc/foreign-words-komlev/fc/slovar-196.htm#zag-607) (Словарь иностранных слов. Комлев Н.Г., 2006)
 
Там, кстати есть немало слов которые являются неологизмами. То есть как раз никак не переводиться, так как заимствование (неологизм). Наверное лучше сначала проверять нет ли нашего спорного слова там, а потом уже переводить его. Время сэкономим, меньше голову ломать))))

**Comment by blademoon** [comment]
self-supervised learning - Самообучение под наблюдением

**Comment by blademoon** [comment]
Corrected the translation and timestamps for the [first part](https://github.com/blademoon/course/tree/main/subtitles/ru) of the video course.
Исправил перевод и временные метки к [первой части](https://github.com/blademoon/course/tree/main/subtitles/ru) видеокурса.

**Comment by blademoon** [comment]
@501Good Я бы придерживался того, что это все же неологизм. Кроме того в МФТИ на лекциях используется "энкодер". Не все неологизмы можно перевести, некоторые просто транслитерацией преобразуют в русское написание. Но это новые слова в языке. Например: "feature" - не переведешь как "фича" (это "признак").

**Comment by blademoon** [comment]
@pdumin Good afternoon. I'm working on the translation of chapter 6. Already 50% done. Please check the box in your first post in this issue.

**Comment by pdumin** [comment]
> @pdumin Good afternoon. I'm working on the translation of chapter 6. Already 50% done. Please check the box in your first post in this issue.

There were no merges last time and I think we can stop working. But I'll check it.

**Comment by blademoon** [comment]
I'm working on the translation of chapter 6 now. Details [here](https://github.com/blademoon/course). The merge is coming soon.

Switched to translate another [course](https://github.com/huggingface/audio-transformers-course/issues/109). That's where we finished.

**Comment by pdumin** [comment]
@blademoon I mean merges to [hf](https://huggingface.co/learn/nlp-course/ru/chapter1/1) site.

**Comment by blademoon** [comment]
From HF team?С уважением, Бойко Артём Николаевич.10:26, 20 декабря 2023 г., Pavel ***@***.***>:
@blademoon I mean merges to hf site.

**Comment by pdumin** [comment]
@blademoon Yes, from them.

**Comment by blademoon** [comment]
@pdumin Понятно. А какие PR у нас зависли? Я могу допереводить оставшиеся части?

**Comment by blademoon** [comment]
@pdumin Mark all notebooks from chapter 6.

**Comment by pdumin** [comment]
@blademoon What chapters are you going to translate next?

**Comment by blademoon** [comment]
@pdumin Chapter 7. I'll go in order, the parts that haven't been translated.

**Comment by blademoon** [comment]
@pdumin Can you tell me in which PR we can look at your translation of `3.mdx`, `3b.mdx`, `4.mdx`, `5.mdx` files ?

**Comment by pdumin** [comment]
@blademoon  [3-4-5](https://github.com/huggingface/course/pull/493/files#diff-9895503f59efa56be4e91f5526fb5476ada9fa2763235331f7a85683e90ea307)

Can't find 3b..🤔

**Comment by blademoon** [comment]
@pdumin It`s not good((( Need to link PR to Issue, and note the current status of translation tasks. Otherwise, we're doing double work.

**Comment by pdumin** [comment]
There is no separate PR for every chapter. I checked how other teams do PR during translation. One big PR for the entire translation. Not separate for each chapter or file.

**Comment by blademoon** [comment]
@pdumin Seriously? We didn't see that when translating the Transformers audio course. No kidding. We did a separate PR for each chapter because each chapter was translated by a different person. That way, the same style of one translator was maintained throughout the whole chapter (in addition to the glossary). This greatly enhances the readability of the material. Besides, this approach is not our invention. Other teams have done it this way. We just modernized it a bit.

**Comment by blademoon** [comment]
@pdumin Mark all Chapter 7 please. I'll translate the whole thing. It wouldn't be good if it happened again.

If you're not quite used to it, you can check out our labeling example.

https://github.com/huggingface/audio-transformers-course/issues/109

**Comment by blademoon** [comment]
@pdumin Good evening, Pavel. Please mark the files `1.mdx`,`2.mdx`,`3.mdx` as translated. Files `4.mdx`,`5.mdx`,`6.mdx`,`7.mdx`,`8.mdx`,`9.mdx` are in the works. I'll do a translation of them as well.

The review of the entire 6th chapter is going on at the moment.

**Comment by blademoon** [comment]
@pdumin Can you translate chapter 8? If it is the same as in the audio course and RL course, it shouldn't be too difficult. Plus it's not too big. If we can do it now, we can close the whole translation. That would be great!

**Comment by pdumin** [comment]
@blademoon Yes, I will translate chapter 8 in next few days. 

Thank you for contribution!

**Comment by blademoon** [comment]
@pdumin Greate! Thanks!)

**Comment by blademoon** [comment]
@pdumin Hello Pavel. 

The first half of the chapter 7 translation has gone to PR.

A small question, as I remember, we agreed that "fine-tuning" should be translated as "дообучение"?

<img width="284" alt="image" src="https://github.com/huggingface/course/assets/17560478/65e56f18-3dc0-451a-89ac-5f4ef2218749">

**Comment by pdumin** [comment]
Hi! I will fix it in future updates. BTW this term was introduced before our agreements.

**Comment by blademoon** [comment]
@pdumin OK. 

Chapter 6 has been published on the official website.

**Comment by blademoon** [comment]
@pdumin Good day Pavel. There have been changes to the course. New parts have been added:

<img width="247" alt="image" src="https://github.com/huggingface/course/assets/17560478/aed85db7-6c29-4342-b5fe-abda9fbf5e7a">

Need to add in first message of this issue.

**Comment by pdumin** [comment]
Thank you. Done

**Comment by pdumin** [comment]
@blademoon WIP, some health problems are slowing me down significantly, but I'm gradually getting there. If I realize that I don’t have time at all, I'll turn to you for help (if appropriate)

**Comment by blademoon** [comment]
@pdumin Well, I wish you a speedy recovery from your illness.

Mark chapter 7, translation completed, review also passed.

I'll do chapter 9 then.

**Comment by pdumin** [comment]
@blademoon Thank you. Fixed, but quality check failed. Have you encountered this before?

```
Run make quality
  make quality
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
python utils/code_formatter.py --check_only
Traceback (most recent call last):
  File "utils/code_formatter.py", line 90, in <module>
    format_all_files(check_only=args.check_only)
  File "utils/code_formatter.py", line 78, in format_all_files
    raise ValueError(f"{len(failures)} files need to be formatted, run `make style`.")
ValueError: 2 files need to be formatted, run `make style`.
make: *** [Makefile:5: quality] Error 1
Error: Process completed with exit code 2.
```

**Comment by blademoon** [comment]
@pdumin Вообщем, добрый вечер Павел. Как твоё здоровье? 
1) Изучи вот [это](https://github.com/huggingface/deep-rl-class/issues/394). Там ты найдёшь много полезного, что существенно облегчит тебе труд.
2) сделай нужно `make style` прежде чем отправлять на проверку. Подробнее описанно вот [здесь](https://github.com/huggingface/course?tab=readme-ov-file#translating-the-course-into-your-language) в пункте "Submit a pull request".

**Comment by pdumin** [comment]
@blademoon Спасибо, пока оставляет желать лучшего. Ни одну главу ранее таким способом не проверял, да и сейчас удивлен, что readme такой большой, в начале таких подробностей не было, изучу. Благодарю.

**Comment by blademoon** [comment]
@pdumin В рамках чисто человеческого отношения. Нас ту не много переводит, но для всех. Я ценю твой труд и старание. Обрати внимание на сообщение [abbbe](https://github.com/abbbe) commented [on Dec 26, 2023](https://github.com/huggingface/deep-rl-class/issues/394#issuecomment-1869161805)

Это существенно упростит тебе жизнь, Марии проверку) Нам же даст возможность довести это дело до конца с более высоким качеством и скоростью. Нет ничего лучше прекрасно сделанной работы, не так ли? ;)

**Comment by blademoon** [comment]
@pdumin I wish you a speedy recovery. If you have any questions, feel free to email me at blademoon@yandex.ru.

**Comment by pdumin** [comment]
@blademoon Thank you. I'll follow your advice.

**Comment by pdumin** [comment]
Chapter 8 translated. PR failed, but local formatting with `make build` gives nothing.
<img width="581" alt="SCR-20240127-lwlo" src="https://github.com/huggingface/course/assets/60391448/2b85575d-a1f1-41c8-9d7e-fe26815e5915">

**Comment by blademoon** [comment]
@pdumin Make style?

**Comment by blademoon** [comment]
@pdumin Started translating chapter 9.

**Comment by blademoon** [comment]
@pdumin Befor PR I'll do only `make style`. I'm previewing what the chapter looks like using only the viewer from PR.

**Comment by blademoon** [comment]
@pdumin Глава 9 практически полностью переведена. Осталось перевести тест в конце главы.

Видел что ты отправил PR с главой 8. Отлично!

https://www.youtube.com/watch?v=94HLyui6eVk

**Comment by blademoon** [comment]
@pdumin Добрый день. Отписал в твой PR в комментарии, в чем возможно ошибка. Исправлять не много. Проверь, возможно репозиторий курса твой, отстаёт от репозитория курса текущего. Но делать это лучше аккуратно. Предварительно сделай резервную копию перевода 8 главы и файла с оглавлением.

**Comment by blademoon** [comment]
The translation of chapter 9 is complete.

**Comment by pdumin** [comment]
@blademoon Добрый день! Вдвойне странно, я сделал sync перед началом перевода. Я все проверю еще раз и попробую, спасибо.

**Comment by blademoon** [comment]
@pdumin Сегодня сможешь внести исправления?

**Comment by pdumin** [comment]
Час назад попробовал – вновь не вышло. Во вторник буду ещё раз делать.

**Comment by blademoon** [comment]
@pdumin Мария взяла твой PR на проверку, подключайся, будем латать...

**Comment by blademoon** [comment]
The translation of the last chapter on course activities is complete.

**Comment by blademoon** [comment]
@pdumin Correction, there are 3 files in Events, not one. Mark the translation and publication of chapter 7.

**Comment by blademoon** [comment]
@pdumin Мои поздравления! Как ревью?)

Отправил Главу 9 и главу с событиями. Пометь 8 главу, что ты ее победил)

**Comment by blademoon** [comment]
@pdumin Субтитры уже сделанные тоже нужно пометить...

**Comment by pdumin** [comment]
@blademoon Ревью ок, исправляется быстро, а вот black проблем подкинул немало. 

Субтитры по 7 переведены. Вторую главу доделаю в выходные.

**Comment by blademoon** [comment]
@pdumin не понял про субтитры. Мне их перевести или ты их уже перевел?

**Comment by pdumin** [comment]
Если есть время – переведи, я их даже не открывал ни разу.

**Comment by blademoon** [comment]
@pdumin сначало доделаем курс. Как примут PR, субтитры сразу после этого буду делать. Стоят в планах тоже.

**Comment by blademoon** [comment]
@pdumin В общем, ревью прошел. глава 9 и последняя глава про события смерджены. Сейчас передышка, мне нужно немного другие дела порешать. Займусь субтитрами немного позднее. А у нас Глава 2 разве не переведена?

**Comment by blademoon** [comment]
@pdumin У меня есть немного свободного времени. Могу заняться переводом 2 главы. Там вроде как не слишком много...

**Comment by pdumin** [comment]
@blademoon если возьмёшься – пиши, буду благодарен.

**Comment by blademoon** [comment]
Взялся. Если что отпишусь. Начну с самого начала. Чтобы единый стиль перевода был.

**Comment by blademoon** [comment]
@pdumin Сделал перевод полностью всей главы 2. Документация собирается. Ждем.

**Comment by blademoon** [comment]
@pdumin Hello Pavel. Mark chapter 2, it's published.

**Comment by pdumin** [comment]
@blademoon Hi! Its already marked.

**Comment by blademoon** [comment]
@pdumin Where?

<img width="713" alt="image" src="https://github.com/huggingface/course/assets/17560478/9d56a058-9dc7-4f82-95c4-038788bf4519">

**Comment by artyomboyko** [comment]
@pdumin Good day Pavel. Can you change my username from `blademoon` to `artyomboyko`?

**Comment by pdumin** [comment]
@artyomboyko Привет, в ближайшие две недели не смогу, но если будет актуально, то с удовольствием.

**Comment by artyomboyko** [comment]
@pdumin Хорошо. Как соберешься - пиши.

**Comment by pdumin** [comment]
@artyomboyko Привет! [Взглянул,](https://github.com/huggingface/agents-course/issues/136) а вы вроде как закончили перевода уже?

**Comment by artyomboyko** [comment]
@pdumin Привет. Ревьювер нужен. Ветку я уже завел здесь https://github.com/huggingface/agents-course/issues/136, как и ранее к issue цепляю PR для удобства работы. За ревью возьмешься? Сам понимаешь, самомого себя ревьюить - так себе затея)
